# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      arg:
        description: 'pattern arg'     
        required: true
        default: '100'  
  

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run pattern
      run: |
        output=$(python pattern.py ${{ github.event.inputs.arg }})
        echo "::set-output name=pattern::$output"
    - name: Print Output
      run : echo "${{ steps.step1.outputs.changelog }}"
